### PR TITLE
More Adventure Updates

### PR DESCRIPTION
**Pull request by givison**
Took all the code out of interpret and into sub-methods

Implemented sub methods for the remaining commands except for the movement command

### CODE REVIEW

**Comment by davidrglass** [comment]
This shit's way more fun than working on the immunology final. =P

**Comment by givison** [comment]
Truth

**Comment by davidrglass** [comment]
Nice. Play decomp is solid. Two things. Do we need startingRoom? It looks like it just gets immediately assigned to currentRoom. Second, do we need directionSet()? Can't the syntax for the else if statement in play just be: else if (DIRECTIONS.contains(command)) { Won't that preclude the need for tokenizing?

**Comment by givison** [comment]
We could just assign the first room to currentRoom immediately, I just liked the aesthetics of assigning starting room as a separate thing, and then putting the player into the starting room during the play method--the player doesn't enter the world until it's finished building I guess? No actual software argument for it being like that though

The problem with checking if the command is in the string of directions is that it will return true if the command is any substring of the directions--i.e. if the command is "t" it would return true, since there's a t in north. So it has to check against a set of full strings--that's my understanding at least

**Comment by davidrglass** [comment]
Haven't we already converted the commands to full words at this point
though?

**Comment by givison** [comment]
Only if it's a legitimate command that's on the synonym list. I want to be able to handle the user entering in nonsense

**Comment by davidrglass** [comment]
Doesn't the final else do that? What's a case that the method handles that
the DIRECTIONS string doesn't?

**Comment by givison** [comment]
If the user inputs "th" as their command, and the if statement only checks if command is a substring of the directions string, then the program will call moveTo(TH)
We could make a case inside moveTo() that handles this case, but I thought it was more elegant to only feed it valid directions

**Pull request merged**
